services:
  db:
    image: postgres:15-alpine
    container_name: fastapi_library_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/home/tejubusion/PycharmProjects/library-fastapi/postgres_data

volumes:
  postgres_data: